name: Manual Windows Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a simple command
        shell: powershell
        run: |
          Write-Host "This is a simple GitHub Actions workflow running on Windows."    
